export const termsData = {
    es: {
        sidebarItems: [
            { id: "services", label: "1. Nuestros servicios" },
            { id: "ip", label: "2. Propiedad intelectual" },
            { id: "representations", label: "3. Representaciones del usuario" },
            { id: "register", label: "4. Registro de usuario" },
            { id: "payments", label: "5. Compras y pagos" },
            { id: "subscriptions", label: "6. Suscripciones y facturación" },
            { id: "prohibited", label: "7. Actividades prohibidas" },
            { id: "ai", label: "8. IA y procesamiento automatizado" },
            { id: "contributions", label: "9. Contribuciones del usuario" },
            { id: "yourip", label: "10. Propiedad intelectual en tus datos" },
            { id: "social", label: "11. Redes sociales" },
            { id: "thirdparty", label: "12. Contenido de terceros" },
            { id: "management", label: "13. Gestión de servicios" },
            { id: "dataroles", label: "14. Roles de datos y privacidad" },
            { id: "copyright", label: "15. Infracciones de derechos de autor" },
            { id: "termination", label: "16. Vigencia y terminación" },
            { id: "modifications", label: "17. Modificaciones e interrupciones" },
            { id: "law", label: "18. Ley aplicable" },
            { id: "disputes", label: "19. Resolución de disputas" },
            { id: "corrections", label: "20. Correcciones" },
            { id: "warranty", label: "21. Renuncia de garantías" },
            { id: "liability", label: "22. Limitación de responsabilidad" },
            { id: "dataprotection", label: "23. Protección de datos" },
            { id: "indemnification", label: "24. Indemnización" },
            { id: "userdata", label: "25. Datos del usuario" },
            { id: "electronic", label: "26. Comunicaciones electrónicas" },
            { id: "general", label: "27. Disposiciones generales" },
            { id: "contact", label: "28. Contacto" },
        ],
        header: {
            badge: "Legal",
            title: "Términos y Condiciones",
            lastUpdated: "Última actualización: 11 de abril de 2026",
            operator: "Operador: BFlow Studio — Edwin Adrián Díaz Henríquez, San Salvador, El Salvador",
        },
        intro: {
            p1: "Somos BFlow Studio, haciendo negocios como BFlow, una empresa registrada en El Salvador. Operamos el sitio web bflow-studio.com y servicios relacionados.",
            p2: "BFlow es una aplicación web de gestión de finanzas personales. No se conecta directamente a cuentas bancarias y no proporciona asesoría financiera, de inversión, fiscal o legal. Al usar nuestros Servicios, aceptas estos Términos.",
        },
        sectionTitles: {
            services: "1. Nuestros servicios",
            ip: "2. Derechos de propiedad intelectual",
            representations: "3. Representaciones del usuario",
            register: "4. Registro de usuario",
            payments: "5. Compras y pagos",
            subscriptions: "6. Suscripciones y facturación",
            prohibited: "7. Actividades prohibidas",
            ai: "8. IA y procesamiento automatizado de datos",
            contributions: "9. Contribuciones generadas por el usuario",
            yourip: "10. Propiedad intelectual en tus datos",
            social: "11. Redes sociales",
            thirdparty: "12. Contenido y sitios web de terceros",
            management: "13. Gestión de servicios",
            dataroles: "14. Roles de datos y política de privacidad",
            copyright: "15. Infracciones de derechos de autor",
            termination: "16. Vigencia y terminación",
            modifications: "17. Modificaciones e interrupciones",
            law: "18. Ley aplicable",
            disputes: "19. Resolución de disputas",
            corrections: "20. Correcciones",
            warranty: "21. Renuncia de garantías",
            liability: "22. Limitación de responsabilidad",
            dataprotection: "23. Protección de datos y transferencias internacionales",
            indemnification: "24. Indemnización",
            userdata: "25. Datos del usuario",
            electronic: "26. Comunicaciones electrónicas, transacciones y firmas",
            general: "27. Disposiciones generales",
            contact: "28. Contacto",
        },
        sections: {
            services: {
                text: "La información proporcionada al usar los Servicios no está destinada a distribución donde violaría la ley. Quienes accedan desde otras ubicaciones lo hacen por su propia iniciativa y son responsables del cumplimiento de leyes locales aplicables.",
            },
            ip: {
                intro: "Somos propietarios o licenciatarios de todos los derechos de propiedad intelectual en nuestros Servicios, incluyendo código fuente, bases de datos, funcionalidad, software, diseños, audio, video, texto, fotografías y gráficos, así como marcas registradas y logos.",
                licenseTitle: "Licencia otorgada:",
                licenseItems: [
                    "Acceder a los Servicios",
                    "Descargar o imprimir contenido al que hayas accedido adecuadamente",
                    "Únicamente para uso personal y no comercial",
                ],
                footer: "Cualquier violación de estos derechos constituirá una violación material y tu acceso a los Servicios terminará inmediatamente.",
            },
            representations: {
                intro: "Al usar los Servicios, representas y garantizas que:",
                items: [
                    "Toda información de registro será verdadera, precisa y completa",
                    "Mantendrás la precisión de tu información actualizada",
                    "Tienes capacidad legal y aceptas estos Términos",
                    "No eres menor de edad en tu jurisdicción",
                    "No accederás mediante medios automatizados o no humanos",
                    "No usarás los Servicios para propósitos ilegales",
                    "Tu uso no violará ninguna ley o regulación aplicable",
                ],
            },
            register: {
                text: "Podrías ser requerido registrarte para usar los Servicios. Aceptas mantener tu contraseña confidencial y serás responsable de todo uso de tu cuenta. Nos reservamos el derecho a eliminar o cambiar un nombre de usuario que determinemos inapropiado u objetable.",
            },
            payments: {
                intro: "Aceptamos las siguientes formas de pago:",
                methods: ["Wompi", "Mastercard", "Visa"],
                footer: "Todos los pagos serán en dólares estadounidenses. Podemos cambiar precios en cualquier momento. Nos reservamos el derecho de rechazar cualquier orden.",
            },
            subscriptions: {
                text: "BFlow ofrece planes de suscripción mensual o anual en dólares estadounidenses. Las suscripciones se renuevan automáticamente. Puedes cancelar en cualquier momento desde tu panel de cuenta.",
                refundLabel: "Política de reembolsos:",
                refundText: "Los reembolsos se evalúan caso a caso. Contacta a support@bflow-studio.com dentro de los 7 días de la transacción.",
            },
            prohibited: {
                intro: "No puedes acceder ni usar los Servicios para ningún propósito diferente al que los ponemos a disposición. Está prohibido:",
                items: [
                    "Uso comercial no autorizado de los Servicios",
                    "Recopilar información de usuarios sin consentimiento",
                    "Usar los Servicios para actividades ilegales o fraudulentas",
                    "Interferir con características de seguridad",
                    "Realizar ingeniería inversa o descompilar el software",
                    "Intentar acceso no autorizado a sistemas",
                    "Transmitir virus u otro código malicioso",
                    "Usar bots, scrapers u otros medios automatizados",
                ],
            },
            ai: {
                intro: "BFlow usa inteligencia artificial para categorizar automáticamente transacciones financieras. Este procesamiento es una función central del servicio.",
                noteTitle: "Importante sobre la IA:",
                noteItems: [
                    "Las categorías sugeridas son orientativas, no definitivas",
                    "Puedes corregir o anular cualquier categorización",
                    "Los datos usados para entrenar modelos son anonimizados",
                    "No tomamos decisiones legalmente vinculantes basadas en IA",
                ],
            },
            contributions: {
                text: "Los Servicios pueden permitirte crear, enviar o publicar contenido. Al hacerlo, nos otorgas una licencia no exclusiva para usar ese contenido únicamente para operar y mejorar el Servicio. Eres responsable del contenido que envías y garantizas que tienes los derechos necesarios.",
            },
            yourip: {
                text: "Tus datos financieros son tuyos. BFlow solo los usa para proporcionar el Servicio. No reclamamos propiedad sobre los datos que introduces. Puedes exportar o eliminar tus datos en cualquier momento.",
            },
            social: {
                text: "Podemos ofrecer funcionalidades de vinculación con redes sociales. Al vincular tu cuenta, aceptas que podemos acceder y usar información de tu perfil social según lo permitido por la plataforma correspondiente y esta Política.",
            },
            thirdparty: {
                text: "Los Servicios pueden contener enlaces a sitios de terceros. No somos responsables por el contenido, precisión o prácticas de esos sitios. La inclusión de un enlace no implica respaldo.",
            },
            management: {
                text: "Nos reservamos el derecho de monitorear los Servicios, tomar acciones legales contra cualquier uso violatorio, rechazar o restringir acceso y gestionar los Servicios para proteger nuestros derechos y el correcto funcionamiento.",
            },
            dataroles: {
                text: "BFlow actúa como Controlador de Datos para información de cuenta y como Procesador para datos financieros que introduces. Para más detalles sobre cómo manejamos tus datos, consulta nuestra Política de Privacidad.",
                privacyLinkText: "Política de Privacidad",
            },
            copyright: {
                text: "Respetamos la propiedad intelectual de terceros. Si crees que algo en los Servicios infringe tu copyright, contacta a legal@bflow-studio.com con los detalles de la infracción.",
            },
            termination: {
                para1: "Estos Términos permanecen vigentes mientras uses los Servicios. Podemos suspender o terminar tu acceso sin previo aviso si violas estos Términos.",
                para2: "Puedes terminar tu cuenta en cualquier momento. Tras la terminación, las disposiciones que por naturaleza deben sobrevivir continuarán en vigor.",
            },
            modifications: {
                text: "Nos reservamos el derecho de cambiar, modificar o eliminar contenido de los Servicios sin previo aviso. No garantizamos disponibilidad ininterrumpida. No seremos responsables por interrupciones, modificaciones o discontinuación de los Servicios.",
            },
            law: {
                intro: "Estos Términos están regidos por las leyes de El Salvador. Para usuarios en otras jurisdicciones, se aplica la mayor protección entre la ley local y la ley de El Salvador.",
                lawItems: [
                    { region: "Unión Europea (EEA)", law: "GDPR prevalece" },
                    { region: "Brasil", law: "LGPD prevalece" },
                    { region: "Colombia", law: "Ley de Habeas Data" },
                    { region: "México", law: "Ley Federal de Protección de Datos" },
                ],
            },
            disputes: {
                para1: "Antes de presentar una demanda, aceptas intentar resolver la disputa informalmente contactando a support@bflow-studio.com.",
                para2: "Las disputas no resueltas se someterán a los tribunales competentes de El Salvador, salvo donde leyes obligatorias de tu jurisdicción establezcan lo contrario.",
            },
            corrections: {
                text: "Podría haber información con errores tipográficos, imprecisiones u omisiones. Nos reservamos el derecho de corregir en cualquier momento sin aviso previo.",
            },
            warranty: {
                asIsLabel: "Los Servicios se proporcionan \"TAL CUAL\" y \"SEGÚN DISPONIBILIDAD\".",
                asIsText: "BFlow no garantiza operación ininterrumpida, sin errores o segura.",
                financialLabel: "Descargo financiero:",
                financialText: "BFlow es una herramienta de rastreo únicamente. No proporciona asesoría financiera, de inversión, fiscal o legal. Eres únicamente responsable de la precisión de tus datos y de consultar profesionales.",
                dataLossLabel: "Pérdida de datos:",
                dataLossText: "Aunque mantenemos respaldos, no garantizamos contra pérdida por fallos técnicos o ataques. Eres responsable de mantener respaldos independientes.",
            },
            liability: {
                capTitle: "Tope de responsabilidad:",
                capText: "La responsabilidad total de BFlow está limitada al mayor entre: (a) cantidades que pagaste en los 12 meses previos, o (b) $50 USD mínimo.",
                capHighlight: "mayor entre:",
                indirect: "No somos responsables por daños indirectos, incidentales, especiales o consecuentes, incluyendo pérdida de ganancias o datos.",
                exceptionsTitle: "Estas limitaciones NO aplican a:",
                exceptions: [
                    "Violaciones de confidencialidad",
                    "Infracción de propiedad intelectual",
                    "Brechas de datos por negligencia grave",
                    "Reclamaciones que no pueden ser limitadas por ley",
                ],
            },
            dataprotection: {
                para1: "BFlow recopila y procesa datos personales según nuestra Política de Privacidad. Los datos pueden transferirse a El Salvador, EE.UU. u otras jurisdicciones.",
                para2: "Al usar los Servicios, consientes que tus datos se transfieran y procesen según sea necesario para operar el Servicio. Usamos encriptación, autenticación segura y auditorías regulares para proteger tu información.",
            },
            indemnification: {
                text: "Aceptas defender, indemnizar y eximirnos de responsabilidad de cualquier pérdida, daño o reclamación hecha por terceros debido a: tus Contribuciones, uso de Servicios, incumplimiento de estos Términos, violación de derechos de terceros o acto dañino hacia otro usuario.",
            },
            userdata: {
                text: "Mantenemos ciertos datos que transmites para monitoreo de rendimiento. Eres únicamente responsable de todos los datos que transmites. Aunque realizamos respaldos regulares, eres responsable de mantener respaldos independientes.",
            },
            electronic: {
                text: "Visitar nuestro sitio y completar formularios constituyen comunicaciones electrónicas. Aceptas que acuerdos, avisos y comunicaciones proporcionadas electrónicamente satisfacen requisitos legales de comunicación por escrito. Aceptas firmas electrónicas y entrega electrónica de avisos y registros.",
            },
            general: {
                para1: "Estos Términos constituyen el acuerdo completo entre tú y nosotros. Si alguna disposición es considerada ilegal o inaplicable, es separable y no afecta la validez de las demás.",
                para2: "No hay relación de socio, empleo o agencia creada entre tú y BFlow. Podemos asignar derechos u obligaciones a terceros en cualquier momento.",
            },
            contact: {
                addressLabel: "Dirección",
                addressValue: "BFlow Studio — San Salvador, El Salvador",
                supportLabel: "Soporte general",
                legalLabel: "Consultas legales",
                openSourceLabel: "Código abierto",
            },
        },
        footerNote: "Última actualización: 11 de abril de 2026 · Efectivos inmediatamente al aceptarlos · Este documento fue originalmente redactado en español y prevalece sobre cualquier traducción.",
    },

    en: {
        sidebarItems: [
            { id: "services", label: "1. Our services" },
            { id: "ip", label: "2. Intellectual property" },
            { id: "representations", label: "3. User representations" },
            { id: "register", label: "4. User registration" },
            { id: "payments", label: "5. Purchases and payments" },
            { id: "subscriptions", label: "6. Subscriptions and billing" },
            { id: "prohibited", label: "7. Prohibited activities" },
            { id: "ai", label: "8. AI and automated processing" },
            { id: "contributions", label: "9. User contributions" },
            { id: "yourip", label: "10. Intellectual property in your data" },
            { id: "social", label: "11. Social media" },
            { id: "thirdparty", label: "12. Third-party content" },
            { id: "management", label: "13. Service management" },
            { id: "dataroles", label: "14. Data roles and privacy" },
            { id: "copyright", label: "15. Copyright infringements" },
            { id: "termination", label: "16. Term and termination" },
            { id: "modifications", label: "17. Modifications and interruptions" },
            { id: "law", label: "18. Applicable law" },
            { id: "disputes", label: "19. Dispute resolution" },
            { id: "corrections", label: "20. Corrections" },
            { id: "warranty", label: "21. Disclaimer of warranties" },
            { id: "liability", label: "22. Limitation of liability" },
            { id: "dataprotection", label: "23. Data protection" },
            { id: "indemnification", label: "24. Indemnification" },
            { id: "userdata", label: "25. User data" },
            { id: "electronic", label: "26. Electronic communications" },
            { id: "general", label: "27. General provisions" },
            { id: "contact", label: "28. Contact" },
        ],
        header: {
            badge: "Legal",
            title: "Terms and Conditions",
            lastUpdated: "Last updated: April 11, 2026",
            operator: "Operator: BFlow Studio — Edwin Adrián Díaz Henríquez, San Salvador, El Salvador",
        },
        intro: {
            p1: "We are BFlow Studio, doing business as BFlow, a company registered in El Salvador. We operate the website bflow-studio.com and related services.",
            p2: "BFlow is a personal finance web application. It does not connect directly to bank accounts and does not provide financial, investment, tax, or legal advice. By using our Services, you agree to these Terms.",
        },
        sectionTitles: {
            services: "1. Our services",
            ip: "2. Intellectual property rights",
            representations: "3. User representations",
            register: "4. User registration",
            payments: "5. Purchases and payments",
            subscriptions: "6. Subscriptions and billing",
            prohibited: "7. Prohibited activities",
            ai: "8. AI and automated data processing",
            contributions: "9. User-generated contributions",
            yourip: "10. Intellectual property in your data",
            social: "11. Social media",
            thirdparty: "12. Third-party content and websites",
            management: "13. Service management",
            dataroles: "14. Data roles and privacy policy",
            copyright: "15. Copyright infringements",
            termination: "16. Term and termination",
            modifications: "17. Modifications and interruptions",
            law: "18. Applicable law",
            disputes: "19. Dispute resolution",
            corrections: "20. Corrections",
            warranty: "21. Disclaimer of warranties",
            liability: "22. Limitation of liability",
            dataprotection: "23. Data protection and international transfers",
            indemnification: "24. Indemnification",
            userdata: "25. User data",
            electronic: "26. Electronic communications, transactions and signatures",
            general: "27. General provisions",
            contact: "28. Contact",
        },
        sections: {
            services: {
                text: "Information provided when using the Services is not intended for distribution where it would violate the law. Those who access from other locations do so on their own initiative and are responsible for compliance with applicable local laws.",
            },
            ip: {
                intro: "We own or are licensees of all intellectual property rights in our Services, including source code, databases, functionality, software, designs, audio, video, text, photographs and graphics, as well as trademarks and logos.",
                licenseTitle: "License granted:",
                licenseItems: [
                    "Access the Services",
                    "Download or print content you have properly accessed",
                    "For personal and non-commercial use only",
                ],
                footer: "Any violation of these rights will constitute a material breach and your access to the Services will be immediately terminated.",
            },
            representations: {
                intro: "By using the Services, you represent and warrant that:",
                items: [
                    "All registration information will be true, accurate and complete",
                    "You will maintain the accuracy of your information",
                    "You have the legal capacity to accept these Terms",
                    "You are not a minor in your jurisdiction",
                    "You will not access through automated or non-human means",
                    "You will not use the Services for illegal purposes",
                    "Your use will not violate any applicable law or regulation",
                ],
            },
            register: {
                text: "You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account. We reserve the right to remove or change a username we determine to be inappropriate or objectionable.",
            },
            payments: {
                intro: "We accept the following payment methods:",
                methods: ["Wompi", "Mastercard", "Visa"],
                footer: "All payments will be in US dollars. We may change prices at any time. We reserve the right to refuse any order.",
            },
            subscriptions: {
                text: "BFlow offers monthly or annual subscription plans in US dollars. Subscriptions renew automatically. You can cancel at any time from your account dashboard.",
                refundLabel: "Refund policy:",
                refundText: "Refunds are evaluated on a case-by-case basis. Contact support@bflow-studio.com within 7 days of the transaction.",
            },
            prohibited: {
                intro: "You may not access or use the Services for any purpose other than that for which we make them available. The following is prohibited:",
                items: [
                    "Unauthorized commercial use of the Services",
                    "Collecting user information without consent",
                    "Using the Services for illegal or fraudulent activities",
                    "Interfering with security features",
                    "Reverse engineering or decompiling the software",
                    "Attempting unauthorized access to systems",
                    "Transmitting viruses or other malicious code",
                    "Using bots, scrapers or other automated means",
                ],
            },
            ai: {
                intro: "BFlow uses artificial intelligence to automatically categorize financial transactions. This processing is a core feature of the service.",
                noteTitle: "Important about AI:",
                noteItems: [
                    "Suggested categories are guidance, not final decisions",
                    "You can correct or override any categorization",
                    "Data used to train models is anonymized",
                    "We do not make legally binding decisions based on AI",
                ],
            },
            contributions: {
                text: "The Services may allow you to create, submit or publish content. By doing so, you grant us a non-exclusive license to use that content solely to operate and improve the Service. You are responsible for the content you submit and warrant that you have the necessary rights.",
            },
            yourip: {
                text: "Your financial data is yours. BFlow only uses it to provide the Service. We do not claim ownership over the data you enter. You can export or delete your data at any time.",
            },
            social: {
                text: "We may offer social media linking features. By linking your account, you agree that we may access and use information from your social profile as permitted by the respective platform and this Policy.",
            },
            thirdparty: {
                text: "The Services may contain links to third-party sites. We are not responsible for the content, accuracy or practices of those sites. Inclusion of a link does not imply endorsement.",
            },
            management: {
                text: "We reserve the right to monitor the Services, take legal action against any violating use, deny or restrict access, and manage the Services to protect our rights and proper operation.",
            },
            dataroles: {
                text: "BFlow acts as Data Controller for account information and as Processor for financial data you enter. For more details on how we handle your data, see our Privacy Policy.",
                privacyLinkText: "Privacy Policy",
            },
            copyright: {
                text: "We respect the intellectual property of third parties. If you believe something in the Services infringes your copyright, contact legal@bflow-studio.com with details of the infringement.",
            },
            termination: {
                para1: "These Terms remain in effect while you use the Services. We may suspend or terminate your access without prior notice if you violate these Terms.",
                para2: "You may terminate your account at any time. After termination, provisions that by their nature should survive will remain in effect.",
            },
            modifications: {
                text: "We reserve the right to change, modify or remove content from the Services without prior notice. We do not guarantee uninterrupted availability. We will not be liable for any interruptions, modifications or discontinuation of the Services.",
            },
            law: {
                intro: "These Terms are governed by the laws of El Salvador. For users in other jurisdictions, the greater protection between local law and El Salvador law applies.",
                lawItems: [
                    { region: "European Union (EEA)", law: "GDPR prevails" },
                    { region: "Brazil", law: "LGPD prevails" },
                    { region: "Colombia", law: "Ley de Habeas Data" },
                    { region: "Mexico", law: "Federal Law on Protection of Personal Data" },
                ],
            },
            disputes: {
                para1: "Before filing a claim, you agree to attempt to resolve the dispute informally by contacting support@bflow-studio.com.",
                para2: "Unresolved disputes will be submitted to the competent courts of El Salvador, except where mandatory laws of your jurisdiction provide otherwise.",
            },
            corrections: {
                text: "There may be information containing typographical errors, inaccuracies or omissions. We reserve the right to correct at any time without prior notice.",
            },
            warranty: {
                asIsLabel: "The Services are provided \"AS IS\" and \"AS AVAILABLE\".",
                asIsText: "BFlow does not guarantee uninterrupted, error-free or secure operation.",
                financialLabel: "Financial disclaimer:",
                financialText: "BFlow is a tracking tool only. It does not provide financial, investment, tax or legal advice. You are solely responsible for the accuracy of your data and for consulting professionals.",
                dataLossLabel: "Data loss:",
                dataLossText: "Although we maintain backups, we do not guarantee against loss due to technical failures or attacks. You are responsible for maintaining independent backups.",
            },
            liability: {
                capTitle: "Liability cap:",
                capText: "BFlow's total liability is limited to the greater of: (a) amounts you paid in the previous 12 months, or (b) $50 USD minimum.",
                capHighlight: "greater of:",
                indirect: "We are not liable for indirect, incidental, special or consequential damages, including loss of profits or data.",
                exceptionsTitle: "These limitations do NOT apply to:",
                exceptions: [
                    "Confidentiality breaches",
                    "Intellectual property infringement",
                    "Data breaches due to gross negligence",
                    "Claims that cannot be limited by law",
                ],
            },
            dataprotection: {
                para1: "BFlow collects and processes personal data in accordance with our Privacy Policy. Data may be transferred to El Salvador, the US or other jurisdictions.",
                para2: "By using the Services, you consent to your data being transferred and processed as necessary to operate the Service. We use encryption, secure authentication and regular audits to protect your information.",
            },
            indemnification: {
                text: "You agree to defend, indemnify and hold us harmless from any loss, damage or claim made by third parties arising from: your Contributions, use of Services, breach of these Terms, violation of third-party rights, or harmful acts toward another user.",
            },
            userdata: {
                text: "We maintain certain data you transmit for performance monitoring. You are solely responsible for all data you transmit. Although we perform regular backups, you are responsible for maintaining independent backups.",
            },
            electronic: {
                text: "Visiting our site and completing forms constitute electronic communications. You agree that agreements, notices and communications provided electronically satisfy legal requirements for written communication. You agree to electronic signatures and electronic delivery of notices and records.",
            },
            general: {
                para1: "These Terms constitute the entire agreement between you and us. If any provision is found to be illegal or unenforceable, it is severable and does not affect the validity of the remaining provisions.",
                para2: "No partnership, employment or agency relationship is created between you and BFlow. We may assign rights or obligations to third parties at any time.",
            },
            contact: {
                addressLabel: "Address",
                addressValue: "BFlow Studio — San Salvador, El Salvador",
                supportLabel: "General support",
                legalLabel: "Legal inquiries",
                openSourceLabel: "Open source",
            },
        },
        footerNote: "Last updated: April 11, 2026 · Effective immediately upon acceptance · This document was originally drafted in Spanish and prevails over any translation.",
    },
};

export const getTermsData = (locale = "es") => termsData[locale] ?? termsData.es;