export const privacyData = {
    es: {
        sidebarItems: [
            { id: "info", label: "1. Qué información recopilamos" },
            { id: "process", label: "2. Cómo procesamos tu información" },
            { id: "share", label: "3. Con quién compartimos tu información" },
            { id: "cookies", label: "4. Cookies y seguimiento" },
            { id: "social", label: "5. Inicios de sesión social" },
            { id: "retention", label: "6. Retención de información" },
            { id: "security", label: "7. Cómo protegemos tu información" },
            { id: "minors", label: "8. Información de menores" },
            { id: "rights", label: "9. Tus derechos de privacidad" },
            { id: "dnt", label: "10. Do-Not-Track y GDPR" },
            { id: "updates", label: "11. Actualizamos esta política" },
            { id: "contact", label: "12. Cómo contactarnos" },
            { id: "delete", label: "13. Revisar, actualizar o eliminar datos" },
            { id: "law", label: "14. Ley aplicable y jurisdicción" },
        ],
        header: {
            badge: "Legal",
            title: "Política de Privacidad",
            lastUpdated: "Última actualización: 11 de abril de 2026",
            operator: "Operador: BFlow Studio — Edwin Adrián Díaz Henríquez, San Salvador, El Salvador",
        },
        keyPoints: [
            { q: "¿Qué información personal procesamos?", a: "Procesamos información que proporcionás voluntariamente al registrarte o usar el servicio." },
            { q: "¿Procesamos información sensible?", a: "No solicitamos datos de categoría especial. Sin embargo, documentos que subas podrían contenerlos incidentalmente — los protegemos con medidas de seguridad reforzadas." },
            { q: "¿Recopilamos información de terceros?", a: "Recopilamos información de perfil de proveedores de login social como Google si elegís ese método." },
            { q: "¿Cómo procesamos tu información?", a: "Para proporcionar el servicio, mejorarlo, comunicarnos con vos, prevenir fraude y cumplir la ley." },
            { q: "¿Cómo protegemos tu información?", a: "Implementamos medidas técnicas y organizacionales. Ningún sistema es 100% seguro." },
        ],
        keyPointsTitle: "Resumen de puntos clave",
        personalInfo: [
            "Nombre completo",
            "Dirección de correo electrónico",
            "Nombre de usuario",
            "Contraseña",
            "Datos de contacto o autenticación",
        ],
        introParagraphs: [
            "BFlow es una aplicación web de gestión de finanzas personales que ayuda a los usuarios a registrar, organizar y analizar ingresos, gastos y actividad financiera en múltiples fuentes de pago, sin conexión directa a bancos.",
            "La plataforma está diseñada únicamente para seguimiento financiero personal y no proporciona asesoría financiera, de inversión, fiscal o legal.",
        ],
        introContact: "Esta Política describe cómo recopilamos, almacenamos, usamos y compartimos tu información personal. Para preguntas, contactá a",
        processRows: [
            ["Correo, usuario, contraseña", "Crear y gestionar cuenta", "Contrato", "Duración de cuenta + 30 días"],
            ["Datos financieros", "Funcionalidad principal", "Contrato", "Duración de cuenta"],
            ["Categorización de transacciones", "Mejorar modelos IA (anonimizado)", "Interés legítimo", "Agregado indefinidamente"],
            ["Correo + actividad de login", "Correos administrativos", "Interés legítimo + Contrato", "Duración de cuenta + 90 días"],
        ],
        shareItems: [
            { name: "AWS", desc: "Hosting, almacenamiento encriptado y envío de correos (SES)" },
            { name: "Cloudflare", desc: "CDN, seguridad y protección DDoS" },
            { name: "Wompi", desc: "Procesamiento de pagos" },
            { name: "Vercel", desc: "Despliegue del frontend" },
        ],
        securityMeasures: [
            "Encriptación en tránsito (TLS/HTTPS) y en reposo",
            "Controles de acceso basados en roles",
            "Auditorías de seguridad regulares",
            "Acuerdos de Procesamiento de Datos con todos los proveedores",
        ],
        rights: [
            "Acceder a tu información personal",
            "Corregir datos imprecisos",
            "Solicitar eliminación de tus datos",
            "Restringir el procesamiento",
            "Portabilidad de datos",
            "Objetar el procesamiento",
            "Retirar consentimiento",
            "Presentar queja ante autoridad de protección de datos",
        ],
        lawItems: [
            { region: "Unión Europea (EEA)", law: "GDPR — Reglamento General de Protección de Datos" },
            { region: "Brasil", law: "LGPD — Lei Geral de Proteção de Dados" },
            { region: "Colombia", law: "Ley de Habeas Data" },
            { region: "México", law: "Ley Federal de Protección de Datos Personales" },
        ],
        sectionTitles: {
            info: "1. ¿Qué información recopilamos?",
            process: "2. ¿Cómo procesamos tu información?",
            share: "3. ¿Con quién compartimos tu información?",
            cookies: "4. ¿Usamos cookies y otras tecnologías de seguimiento?",
            social: "5. ¿Cómo manejamos tus inicios de sesión social?",
            retention: "6. ¿Cuánto tiempo retenemos tu información?",
            security: "7. ¿Cómo protegemos tu información?",
            minors: "8. ¿Recopilamos información de menores?",
            rights: "9. ¿Cuáles son tus derechos de privacidad?",
            dnt: "10. Controles de Do-Not-Track y cumplimiento GDPR",
            updates: "11. ¿Actualizamos esta política?",
            contact: "12. ¿Cómo contactarnos sobre esta política?",
            delete: "13. ¿Cómo revisar, actualizar o eliminar tus datos?",
            law: "14. Ley aplicable, jurisdicción y cumplimiento internacional",
        },
        sections: {
            info: {
                intro: "Recopilamos información personal que nos das voluntariamente cuando te registrás, expresás interés en nuestros servicios o contactás con nosotros.",
                personalInfoTitle: "Información personal que proporcionás:",
                socialTitle: "Datos de Login Social:",
                socialDesc: "Ofrecemos registro vía cuenta Google. Si elegís este método, recopilaremos nombre, correo y foto de perfil. Solicitamos solo la información mínima necesaria.",
                sensitiveNoteLabel: "Nota sobre datos sensibles:",
                sensitiveNoteDesc: "BFlow no solicita ni recopila intencionalmente datos de categoría especial (origen racial, salud, orientación sexual, etc.). Sin embargo, documentos o imágenes que subás podrían contenerlos incidentalmente. Los protegemos con medidas de seguridad reforzadas.",
            },
            process: {
                intro: "Procesamos tu información para proporcionar, mejorar y administrar nuestros Servicios, comunicarnos con vos, prevenir fraude y cumplir la ley.",
                tableHeaders: ["Tipo de Dato", "Propósito", "Base Legal", "Retención"],
            },
            share: {
                intro: "Compartimos información en situaciones específicas con terceros de confianza que nos ayudan a operar el servicio:",
                footer: "No vendemos ni alquilamos tu información personal a terceros con fines de marketing.",
            },
            cookies: {
                text: "Podemos usar cookies y tecnologías similares para recopilar información cuando interactuás con nuestros Servicios. Podés configurar tu navegador para rechazar cookies, aunque esto puede afectar algunas funcionalidades.",
            },
            social: {
                text: "Si elegís registrarte usando Google, recibiremos acceso a cierta información de tu cuenta. Usamos esa información solo para crear tu perfil en BFlow. Nuestro uso cumple con la Política de Datos de Usuarios de Servicios de Google API, incluyendo los requisitos de Uso Limitado.",
            },
            retention: {
                para1: "Retenemos tu información personal solo el tiempo necesario para los fines descritos en esta Política, a menos que la ley requiera períodos de retención más largos.",
                para2: "Cuando eliminás tu cuenta, procesamos la solicitud dentro de los 30 días. Algunos datos pueden retenerse por períodos adicionales para cumplir obligaciones legales.",
            },
            security: {
                intro: "Implementamos medidas técnicas y organizacionales apropiadas incluyendo:",
                footer: "Sin embargo, ningún sistema de seguridad es impenetrable. No podemos garantizar seguridad absoluta.",
            },
            minors: {
                text: "BFlow no está dirigido a menores de 18 años. No recopilamos intencionalmente información personal de menores. Si descubrimos que hemos recopilado información de un menor, la eliminaremos de inmediato. Si sos padre o tutor y creés que tu hijo nos ha proporcionado información, contactá a",
            },
            rights: {
                intro: "Dependiendo de tu ubicación, podés tener los siguientes derechos:",
                footer: "Para ejercer estos derechos, contactá a",
            },
            dnt: {
                para1: "Actualmente no respondemos a señales DNT. Si en el futuro debe adoptarse un estándar que debamos seguir, lo informaremos en una versión revisada de esta Política.",
                gdprTitle: "Tus derechos GDPR (si estás en la EEA):",
                gdprDesc: "Si estás en la Zona Económica Europea, GDPR aplica a nuestro procesamiento de tu información. Protegemos transferencias internacionales mediante Acuerdos de Procesamiento de Datos (DPA) con Cláusulas Contractuales Estándar (SCCs) aprobadas por la Comisión Europea.",
            },
            updates: {
                text: "Podemos actualizar esta Política ocasionalmente. La versión actualizada se indicará por una fecha de \"Última actualización\". Si hacemos cambios materiales, te notificaremos publicando un aviso prominente o enviándote una notificación directa.",
            },
            contact: {
                postalLabel: "Correo postal",
                postalValue: "BFlow Studio — San Salvador, El Salvador",
                supportLabel: "Soporte general",
                privacyLabel: "Preguntas de privacidad",
            },
            delete: {
                text: "Según las leyes aplicables de tu país, podés tener derecho a solicitar acceso a tu información personal, corregir imprecisiones o eliminarla.",
                btnText: "Solicitar gestión de mis datos →",
            },
            law: {
                intro: "Esta Política está regida por las leyes de El Salvador. Para usuarios en otras jurisdicciones, si la ley local ofrece mayor protección, aplica la mayor protección.",
            },
        },
        footerNote: "Última actualización: 11 de abril de 2026 · Este documento fue originalmente redactado en español. En caso de conflicto con traducciones, esta versión prevalece.",
    },

    en: {
        sidebarItems: [
            { id: "info", label: "1. What information we collect" },
            { id: "process", label: "2. How we process your information" },
            { id: "share", label: "3. Who we share your information with" },
            { id: "cookies", label: "4. Cookies and tracking" },
            { id: "social", label: "5. Social login" },
            { id: "retention", label: "6. Data retention" },
            { id: "security", label: "7. How we protect your information" },
            { id: "minors", label: "8. Minors' information" },
            { id: "rights", label: "9. Your privacy rights" },
            { id: "dnt", label: "10. Do-Not-Track and GDPR" },
            { id: "updates", label: "11. We update this policy" },
            { id: "contact", label: "12. How to contact us" },
            { id: "delete", label: "13. Review, update or delete data" },
            { id: "law", label: "14. Applicable law and jurisdiction" },
        ],
        header: {
            badge: "Legal",
            title: "Privacy Policy",
            lastUpdated: "Last updated: April 11, 2026",
            operator: "Operator: BFlow Studio — Edwin Adrián Díaz Henríquez, San Salvador, El Salvador",
        },
        keyPoints: [
            { q: "What personal information do we process?", a: "We process information you voluntarily provide when signing up or using the service." },
            { q: "Do we process sensitive information?", a: "We do not request special category data. However, files you upload may incidentally contain it — we protect it with enhanced security measures." },
            { q: "Do we collect third-party information?", a: "We collect profile data from social login providers like Google if you choose that method." },
            { q: "How do we process your information?", a: "To provide the service, improve it, communicate with you, prevent fraud, and comply with the law." },
            { q: "How do we protect your information?", a: "We implement technical and organizational measures. No system is 100% secure." },
        ],
        keyPointsTitle: "Summary of key points",
        personalInfo: [
            "Full name",
            "Email address",
            "Username",
            "Password",
            "Contact or authentication details",
        ],
        introParagraphs: [
            "BFlow is a personal finance web application that helps users track, organize, and analyze income, expenses, and financial activity across multiple payment sources without direct bank connectivity.",
            "The platform is designed only for personal finance tracking and does not provide financial, investment, tax, or legal advice.",
        ],
        introContact: "This Policy describes how we collect, store, use and share your personal information. For questions, contact",
        processRows: [
            ["Email, username, password", "Create and manage account", "Contract", "Account duration + 30 days"],
            ["Financial data", "Core functionality", "Contract", "Account duration"],
            ["Transaction categorization", "Improve AI models (anonymized)", "Legitimate interest", "Stored indefinitely"],
            ["Email + login activity", "Administrative emails", "Legitimate interest + Contract", "Account duration + 90 days"],
        ],
        shareItems: [
            { name: "AWS", desc: "Hosting, encrypted storage, and email delivery (SES)" },
            { name: "Cloudflare", desc: "CDN, security, and DDoS protection" },
            { name: "Wompi", desc: "Payment processing" },
            { name: "Vercel", desc: "Frontend deployment" },
        ],
        securityMeasures: [
            "Encryption in transit (TLS/HTTPS) and at rest",
            "Role-based access controls",
            "Regular security audits",
            "Data Processing Agreements with all providers",
        ],
        rights: [
            "Access your personal information",
            "Correct inaccurate data",
            "Request deletion of your data",
            "Restrict processing",
            "Data portability",
            "Object to processing",
            "Withdraw consent",
            "File a complaint with the data protection authority",
        ],
        lawItems: [
            { region: "European Union (EEA)", law: "GDPR — General Data Protection Regulation" },
            { region: "Brazil", law: "LGPD — Lei Geral de Proteção de Dados" },
            { region: "Colombia", law: "Ley de Habeas Data" },
            { region: "Mexico", law: "Federal Law on Protection of Personal Data" },
        ],
        sectionTitles: {
            info: "1. What information do we collect?",
            process: "2. How do we process your information?",
            share: "3. Who do we share your information with?",
            cookies: "4. Do we use cookies and other tracking technologies?",
            social: "5. How do we handle your social logins?",
            retention: "6. How long do we retain your information?",
            security: "7. How do we protect your information?",
            minors: "8. Do we collect information from minors?",
            rights: "9. What are your privacy rights?",
            dnt: "10. Do-Not-Track controls and GDPR compliance",
            updates: "11. Do we update this policy?",
            contact: "12. How to contact us about this policy?",
            delete: "13. How to review, update or delete your data?",
            law: "14. Applicable law, jurisdiction and international compliance",
        },
        sections: {
            info: {
                intro: "We collect personal information you voluntarily provide when you register, express interest in our services, or contact us.",
                personalInfoTitle: "Personal information you provide:",
                socialTitle: "Social Login Data:",
                socialDesc: "We offer registration via Google account. If you choose this method, we will collect your name, email, and profile photo. We only request the minimum information necessary.",
                sensitiveNoteLabel: "Note on sensitive data: ",
                sensitiveNoteDesc: "BFlow does not intentionally request or collect special category data (racial origin, health, sexual orientation, etc.). However, documents or images you upload may incidentally contain such data. We protect it with enhanced security measures.",
            },
            process: {
                intro: "We process your information to provide, improve, and administer our Services, communicate with you, prevent fraud, and comply with the law.",
                tableHeaders: ["Data Type", "Purpose", "Legal Basis", "Retention"],
            },
            share: {
                intro: "We share information in specific situations with trusted third parties who help us operate the service:",
                footer: "We do not sell or rent your personal information to third parties for marketing purposes.",
            },
            cookies: {
                text: "We may use cookies and similar technologies to collect information when you interact with our Services. You can set your browser to refuse cookies, although this may affect some functionality.",
            },
            social: {
                text: "If you choose to register using Google, we will receive access to certain information from your account. We use that information only to create your BFlow profile. Our use complies with the Google API Services User Data Policy, including the Limited Use requirements.",
            },
            retention: {
                para1: "We retain your personal information only as long as necessary for the purposes described in this Policy, unless the law requires longer retention periods.",
                para2: "When you delete your account, we process the request within 30 days. Some data may be retained for additional periods to fulfill legal obligations.",
            },
            security: {
                intro: "We implement appropriate technical and organizational measures including:",
                footer: "However, no security system is impenetrable. We cannot guarantee absolute security.",
            },
            minors: {
                text: "BFlow is not directed to minors under 18 years of age. We do not intentionally collect personal information from minors. If we discover we have collected information from a minor, we will delete it immediately. If you are a parent or guardian and believe your child has provided us with information, contact",
            },
            rights: {
                intro: "Depending on your location, you may have the following rights:",
                footer: "To exercise these rights, contact",
            },
            dnt: {
                para1: "We currently do not respond to DNT signals. If a standard is adopted in the future that we must follow, we will inform you in a revised version of this Policy.",
                gdprTitle: "Your GDPR rights (if you are in the EEA):",
                gdprDesc: "If you are in the European Economic Area, GDPR applies to our processing of your information. We protect international transfers through Data Processing Agreements (DPA) with Standard Contractual Clauses (SCCs) approved by the European Commission.",
            },
            updates: {
                text: "We may update this Policy occasionally. The updated version will be indicated by a \"Last updated\" date. If we make material changes, we will notify you by posting a prominent notice or sending you a direct notification.",
            },
            contact: {
                postalLabel: "Mailing address",
                postalValue: "BFlow Studio — San Salvador, El Salvador",
                supportLabel: "General support",
                privacyLabel: "Privacy inquiries",
            },
            delete: {
                text: "Under applicable laws in your country, you may have the right to request access to your personal information, correct inaccuracies, or delete it.",
                btnText: "Request data management →",
            },
            law: {
                intro: "This Policy is governed by the laws of El Salvador. For users in other jurisdictions, if local law provides greater protection, that protection applies.",
            },
        },
        footerNote: "Last updated: April 11, 2026 · This document was originally drafted in Spanish. In case of conflict with translations, the Spanish version prevails.",
    },
};

export const getPrivacyData = (locale = "es") => privacyData[locale] ?? privacyData.es;